contact/urls.py
from django.urls import path
from.views import *

app_name = 'cont'
urlpatterns = [
    path('', Cont, name='cont')
]

main/urls.py
from django.urls import path
from.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', Home, name='home'),
    path('covid/', covid, name='covid'),
    path('shohada/', shohada, name='shoh'),
    path('shahr/', shahr, name='shahr'),
    path('det/<id>', Detail, name='det'),
    path('es', Es, name='es')
]

web/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cont/', include('contact.urls'))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=200)
    sub = models.CharField(max_length=100)
    text = models.TextField()

    def __str__(self):
        return self.name

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Posts(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateField(auto_now=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to = 'media', default = None)
    cat = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[0:100] + ' ...'

contact/views.py
from django.shortcuts import redirect, render
from .models import Contact

def Cont(request):

    if request.method == 'POST':
        data = request.POST
        text = Contact.objects.create(name=data['name'], sub=data['sub'], text=data['message'])
        return redirect('home')

    return render(request, 'contact/cont.html')

main/views.py
from django.shortcuts import redirect, render
from .models import *

def Home(request):
    posts = Posts.objects.all()
    latest_posts = posts[::-1][:4]
    context = {'posts':posts, 'latest':latest_posts}
    return render(request, 'main/index.html', context)

def covid(request):
    posts = Posts.objects.all().filter(cat='کرونا')
    context = {'posts':posts}
    return render(request, 'main/covid.html', context)

def shohada(request):
    posts = Posts.objects.all().filter(cat='شهدا')
    context = {'posts':posts}
    return render(request, 'main/shoh.html', context)

def shahr(request):
    posts = Posts.objects.all().filter(cat='شهر')
    context = {'posts': posts}
    return render(request, 'main/shah.html', context)

def Es(request):
    return render(request, 'main/es.html')

def Detail(request, id):
    post = Posts.objects.get(id=id)
    context = {'post':post}
    return render(request, 'main/det.html', context)

contact/templates/contact/cont.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>شما بنویسید</title>

    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'unicons.css' %}">
    <link rel="stylesheet" href="{% static 'owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'owl.theme.default.min.css' %}">

    <!-- MAIN STYLE -->
    <link rel="stylesheet" href="{% static 'tooplate-style.css' %}">

    <!--

Tooplate 2115 Marvel

https://www.tooplate.com/view/2115-marvel

-->
</head>

<body style="background-image: url(../contact/default-img.jpg);">
<div class="col-lg-6 col-12" style="margin-top: 10%;">
    <div class="contact-form">
        <h2 class="mb-4" style="text-align: center;">شما هم مطلبی دارید ؟</h2>
        <h5 style="text-align: center;">میتوانید در رابطه با موضوع های این وبلاگ نوشته های خود را منتشر کنید</h5>
        <h6 style="text-align: center; color: rebeccapurple;">نوشته شما بعد از تایید مدریت در سایت قرار خواهد گرفت</h6>
        <form action="{% url 'cont:cont' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-12">
                    <input type="text" class="form-control" name="name" placeholder="نام شما" id="name">
                </div>

                <div class="col-lg-6 col-12">
                    <input type="text" class="form-control" name="sub" placeholder="موضوع" id="email">
                </div>

                <div class="col-12">
                    <textarea name="message" rows="6" class="form-control" id="message"
                        placeholder="نوشته شما"></textarea>
                </div>
            
                <button type="submit" class="ml-lg-auto col-lg-5 col-12" style="border: 0; background-color: black; border-radius: 10px; color: white; margin-right: 29%; height: 50px;">ارسال</button>
            </div>
        </form>
    </div>
</div>
</body>
</html>

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <title>weblog</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Fonts -->
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/mediumish.css' %}" rel="stylesheet">
</head>

<body>

    <!-- Begin Nav
================================================== -->
    <nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <!-- Begin Logo -->
            <a class="navbar-brand" href="{% url 'home' %}">
                <h3>ایران زیبا</h3>
            </a>
            <!-- End Logo -->
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <!-- Begin Menu -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cont:cont' %}">شما بنویسید</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'covid' %}">مقابله با کرونا</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'es' %}">گامی به سوی استقلال</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shahr' %}">شهری که دوستش داریم</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shoh' %}">شهدا</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">صفحه اصلی <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <!-- End Menu -->
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    
    <!-- Begin Footer
    	================================================== -->
    <div class="footer" dir="rtl">
        <p class="pull-left">
            ایران زیبا
        </p>
        <p class="pull-right">
            طراحی و ساخت توسط <a target="_blank" href="https://www.linkedin.com/in/imioker/">ایمان قهرشکن</a>
        </p>
        <div class="clearfix">
        </div>
    </div>
    <!-- End Footer
    	================================================== -->
    
    </div>
    <!-- /.container -->
    
    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    </body>
    
    </html>

main/templates/main/covid.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<!-- Begin Site Title
================================================== -->
<div class="container" dir="rtl">
    <div class="mainheading">
        <h1 class="sitetitle" style="font-family: 'yekan';">نوشته هایی درباره کرونا</h1>
    </div>
    <!-- End Site Title
================================================== -->


    <!-- Begin List Posts
	================================================== -->
    <section class="recent-posts">
        <div class="section-title">
            <h2><span>همه پست ها</span></h2>
        </div>
        <div class="card-columns listrecent">
            {% for post in posts %}
            <!-- begin post -->
            <div class="card">
                <a href="post.html">
                    <img class="img-fluid" src="{{post.image.url}}" alt="">
                </a>
                <div class="card-block">
                    <h2 class="card-title"><a href="post.html">{{post.title}}</a></h2>
                    <h4 class="card-text">{{post.snippet}}</h4>
                    <div class="metafooter">
                        <div class="wrapfooter">
                            <span class="author-meta">
                                <span class="post-name">{{post.author}}</span><br />
                                <span class="post-date">{{post.date}}</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end post -->
            {% endfor %}

            <!-- begin post -->
            <div class="card">
                <a href="{% url 'cont:cont' %}">
                    <img class="img-fluid" src="{% static 'img/add.jpg' %}" alt="">
                </a>
                <div class="card-block">
                    <h2 class="card-title"><a href="post.html">شما بنویسید !</a></h2>
                </div>
            </div>
            <!-- end post -->

        </div>
    </section>

{% endblock content %}

main/templates/main/det.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<div class="container" dir="rtl">
    <div class="row">

        <!-- Begin Fixed Left Share -->
        <div class="col-md-2 col-xs-12">
            <div class="share">
                
            </div>
        </div>
        <!-- End Fixed Left Share -->

        <!-- Begin Post -->
        <div class="col-md-8 col-md-offset-2 col-xs-12">
            <div class="mainheading">

                

                <h1 class="posttitle">{{post.title}}</h1>

            </div>

            <!-- Begin Featured Image -->
            <img class="featured-image img-fluid" src="{{post.image.url}}" alt="">
            <!-- End Featured Image -->

            <!-- Begin Post Content -->
            <div class="article-post">
                <p>
                    {{post.content}}
                </p>

        </div>
        <!-- End Post -->

    </div>
</div>
<!-- End Article
================================================== -->
{% endblock content %}

main/templates/main/es.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="mainheading" dir="rtl">
        <h1 class="sitetitle" style="font-family: 'yekan';">هنوز مطلبی برای این موضوع نوشته نشده است</h1>
        <p class="lead">
            شما می توانید از <a href="{% url 'cont:cont' %}">اینجا</a> بنوسید
        </p>
    </div>
{% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<!-- Begin Site Title
================================================== -->
<div class="container" dir="rtl">
	<div class="mainheading">
		<h1 class="sitetitle" style="font-family: 'yekan';">ایران زیباتر</h1>
		<p class="lead">
			 مردمی شاد تر و حالی خوب تر
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin Featured
	================================================== -->
	<section class="featured-posts">
	<div class="section-title">
		<h2><span>جدیدترین پست ها</span></h2>
	</div>
	<div class="card-columns listfeaturedtag">

		
		<!-- begin post -->
		<div class="card">
			<div class="row">
				<div class="col-md-5 wrapthumbnail">
					<a href="{% url 'det' post.id %}">
						<div class="thumbnail" style="background-image:url({% static 'img/sh.jpg' %});">
						</div>
					</a>
				</div>
				<div class="col-md-7">
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'det' post.id %}">داستان سه شهیدی که کمتر شنیده ایم</a></h2>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="author-meta">
								<span class="post-name">ایمان قهرشکن</span><br/>
								<span class="post-date">1.2022</span>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end post -->

		<!-- begin post -->
		<div class="card">
			<div class="row">
				<div class="col-md-5 wrapthumbnail">
					<a href="{% url 'det' post.id %}">
						<div class="thumbnail" style="background-image:url({% static 'img/es.jpg' %});">
						</div>
					</a>
				</div>
				<div class="col-md-7">
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'det' post.id %}">مقابله با اضطراب کرونا</a></h2>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="author-meta">
								<span class="post-name">ایمان قهرشکن</span><br/>
								<span class="post-date">1.2022</span>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end post -->

		<!-- begin post -->
		<div class="card">
			<div class="row">
				<div class="col-md-5 wrapthumbnail">
					<a href="{% url 'det' post.id %}">
						<div class="thumbnail" style="background-image:url({% static 'img/co.jpg' %});">
						</div>
					</a>
				</div>
				<div class="col-md-7">
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'det' post.id %}">از کرونا دور بمانیم</a></h2>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="author-meta">
								<span class="post-name">ایمان قهرشکن</span><br/>
								<span class="post-date">1.2022</span>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end post -->

		<!-- begin post -->
		<div class="card">
			<div class="row">
				<div class="col-md-5 wrapthumbnail">
					<a href="{% url 'det' post.id %}">
						<div class="thumbnail" style="background-image:url({% static 'img/do.jpg' %});">
						</div>
					</a>
				</div>
				<div class="col-md-7">
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'det' post.id %}">دوچرخه | برای شهرم</a></h2>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="author-meta">
								<span class="post-name">{{post.author}}</span><br/>
								<span class="post-date">{{post.date}}</span>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end post -->
		

	</div>
	</section>
	<!-- End Featured
	================================================== -->

	<!-- Begin List Posts
	================================================== -->
	<section class="recent-posts">
	<div class="section-title">
		<h2><span>همه پست ها</span></h2>
	</div>
	<div class="card-columns listrecent">
		{% for post in posts %}
		<!-- begin post -->
		<div class="card">
			<a href="{% url 'det' post.id %}">
				<img class="img-fluid" src="{{post.image.url}}" alt="">
			</a>
			<div class="card-block">
				<h2 class="card-title"><a href="{% url 'det' post.id %}">{{post.title}}</a></h2>
				<h4 class="card-text">{{post.snippet}}</h4>
				<div class="metafooter">
					<div class="wrapfooter">
						<span class="author-meta">
						<span class="post-name">{{post.author}}</span><br/>
						<span class="post-date">{{post.date}}</span>
						</span>
					</div>
				</div>
			</div>
		</div>
		<!-- end post -->
		{% endfor %}

		<!-- begin post -->
		<div class="card">
			<a href="{% url 'cont:cont' %}">
				<img class="img-fluid" src="{% static 'img/add.jpg' %}" alt="">
			</a>
			<div class="card-block">
				<h2 class="card-title"><a href="{% url 'cont:cont' %}">شما بنویسید !</a></h2>
			</div>
		</div>
		<!-- end post -->

	</div>
	</section>
	
{% endblock content %}

main/templates/main/shah.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<!-- Begin Site Title
================================================== -->
<div class="container" dir="rtl">
    <div class="mainheading">
        <h1 class="sitetitle" style="font-family: 'yekan';">نوشته هایی برای شهرمان</h1>
    </div>
    <!-- End Site Title
================================================== -->


    <!-- Begin List Posts
	================================================== -->
    <section class="recent-posts">
        <div class="section-title">
            <h2><span>همه پست ها</span></h2>
        </div>
        <div class="card-columns listrecent">
            {% for post in posts %}
            <!-- begin post -->
            <div class="card">
                <a href="post.html">
                    <img class="img-fluid" src="{{post.image.url}}" alt="">
                </a>
                <div class="card-block">
                    <h2 class="card-title"><a href="post.html">{{post.title}}</a></h2>
                    <h4 class="card-text">{{post.snippet}}</h4>
                    <div class="metafooter">
                        <div class="wrapfooter">
                            <span class="author-meta">
                                <span class="post-name">{{post.author}}</span><br />
                                <span class="post-date">{{post.date}}</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end post -->
            {% endfor %}

            <!-- begin post -->
            <div class="card">
                <a href="{% url 'cont:cont' %}">
                    <img class="img-fluid" src="{% static 'img/add.jpg' %}" alt="">
                </a>
                <div class="card-block">
                    <h2 class="card-title"><a href="post.html">شما بنویسید !</a></h2>
                </div>
            </div>
            <!-- end post -->

        </div>
    </section>

    {% endblock content %}

main/templates/main/shoh.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<!-- Begin Site Title
================================================== -->
<div class="container" dir="rtl">
    <div class="mainheading">
        <h1 class="sitetitle" style="font-family: 'yekan';">نوشته هایی درباره شهدا</h1>
    </div>
    <!-- End Site Title
================================================== -->


    <!-- Begin List Posts
	================================================== -->
    <section class="recent-posts">
        <div class="section-title">
            <h2><span>همه پست ها</span></h2>
        </div>
        <div class="card-columns listrecent">
            {% for post in posts %}
            <!-- begin post -->
            <div class="card">
                <a href="post.html">
                    <img class="img-fluid" src="{{post.image.url}}" alt="">
                </a>
                <div class="card-block">
                    <h2 class="card-title"><a href="post.html">{{post.title}}</a></h2>
                    <h4 class="card-text">{{post.snippet}}</h4>
                    <div class="metafooter">
                        <div class="wrapfooter">
                            <span class="author-meta">
                                <span class="post-name">{{post.author}}</span><br />
                                <span class="post-date">{{post.date}}</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end post -->
            {% endfor %}

            <!-- begin post -->
            <div class="card">
                <a href="{% url 'cont:cont' %}">
                    <img class="img-fluid" src="{% static 'img/add.jpg' %}" alt="">
                </a>
                <div class="card-block">
                    <h2 class="card-title"><a href="post.html">شما بنویسید !</a></h2>
                </div>
            </div>
            <!-- end post -->

        </div>
    </section>

    {% endblock content %}